pcm.loop48 {
    type plug
    slave {
        pcm "hw:Loopback,0,0"
        rate 48000
        format S16_LE
        channels 2
    }
}
pcm.multi_out {
    type multi
    slaves.a.pcm "hw:sndrpihifiberry,0"
    slaves.a.channels 2
    slaves.b.pcm "loop48"
    slaves.b.channels 2
    bindings.0.slave a
    bindings.0.channel 0
    bindings.1.slave a
    bindings.1.channel 1
    bindings.2.slave b
    bindings.2.channel 0
    bindings.3.slave b
    bindings.3.channel 1
}
pcm.caldera_tap {
    type route
    slave.pcm "multi_out"
    slave.channels 4
    ttable.0.0 1
    ttable.1.1 1
    ttable.0.2 1
    ttable.1.3 1
}
